global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "gateway-service"
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - gateway-service:8080

  - job_name: "email-service"
    scheme: http
    metrics_path: /metrics
    static_configs:
      - targets:
          - email-service:8080
